### ISSUE TITLE
split storage local and storage cookie

### ISSUE THREAD

**Issue by mathpere** [angular-translate/bower-angular-translate-storage-local#7]
Hi,

Why this module depends on angular-translate-storage-cookie?

The cookie fallback should be handled by the client app itself or a third generic storage module, but not by this module itself. 

Dependency tree will become:

```angular-translate-storage-cookie``` (no dependencies)
 
```angular-translate-storage-local```  (no dependencies)

And an optional new module which would handle fallback between local and cookie:

```
angular-translate-storage 
    |--angular-translate-storage-cookie
    |--angular-translate-storage-local
```

**Comment by knalli** [comment]
Hi @mathpere 

1. It depends on cookies because of the internal fallback. Since this plugin uses window.localStorage directly, there would be no fallback by an possible (except a polyfill for window.localStorage itself). Afaik the core module itself relies on a storage module which works any times. There is no fallback layer.
2. This repository is only for bower availability;  issues should be handled in the main repo (even it is related to this here).

We like to see enhancements, so make a PR! :)

**Comment by mathpere** [comment]
Thanks for your quick feedback.

Yes, like I said, I've seen the internal fallback but I didn't understand why this fallback is done by this module rather than the app itself or an optional third generic storage module.

**Comment by knalli** [comment]
I cannot say either. An additional storage wrapper plugin is definitely an overkill, and a handling in the core was not done. As I already said, that could be enhanced.

**Comment by mathpere** [comment]
Matter of perspective, in my use case, the overkill is this fallback :)

For a mobile web app with specific targeted platforms where local storage will be always present, angular-cookies and angular-translate-storage-cookie are required but won't never be used.

**Comment by atroy** [comment]
@knalli same here.. Let the developer check for localstorage and add cookie storage if necessary. On mobile we want to have small js - for now we have to build our own customstorage doing the same, but without fallback ;)
